package net.gtransagent.internal

import java.util.*

object LangCodes {
    val langCodes: Map<String, String>
        get() = mapOf(
            "ab" to "Abkhazian",
            "aa" to "Afar",
            "af" to "Afrikaans",
            "ak" to "Akan",
            "sq" to "Albanian",
            "am" to "Amharic",
            "ar" to "Arabic",
            "an" to "Aragonese",
            "hy" to "Armenian",
            "as" to "Assamese",
            "av" to "Avaric",
            "ae" to "Avestan",
            "ay" to "Aymara",
            "az" to "Azerbaijani",
            "bm" to "Bambara",
            "ba" to "Bashkir",
            "eu" to "Basque",
            "be" to "Belarusian",
            "bn" to "Bengali",
            "bi" to "Bislama",
            "bs" to "Bosnian",
            "br" to "Breton",
            "bg" to "Bulgarian",
            "my" to "Burmese",
            "ca" to "Catalan",
            "ch" to "Chamorro",
            "ce" to "Chechen",
            "ny" to "Chichewa",
            "zh" to "Chinese",
            "zh-CN" to "Chinese (Simplified)", // Common variant
            "zh-TW" to "Chinese (Traditional)",
            "zh_Hans" to "Chinese (Simplified)", // Common variant
            "zh_Hant" to "Chinese (Traditional)",
            "cv" to "Chuvash",
            "kw" to "Cornish",
            "co" to "Corsican",
            "cr" to "Cree",
            "hr" to "Croatian",
            "cs" to "Czech",
            "da" to "Danish",
            "dv" to "Divehi",
            "nl" to "Dutch",
            "dz" to "Dzongkha",
            "en" to "English",
            "eo" to "Esperanto",
            "et" to "Estonian",
            "ee" to "Ewe",
            "fo" to "Faroese",
            "fj" to "Fijian",
            "fi" to "Finnish",
            "fr" to "French",
            "ff" to "Fula",
            "gl" to "Galician",
            "ka" to "Georgian",
            "de" to "German",
            "el" to "Greek",
            "gn" to "Guaraní",
            "gu" to "Gujarati",
            "ht" to "Haitian Creole",
            "ha" to "Hausa",
            "he" to "Hebrew",
            "hz" to "Herero",
            "hi" to "Hindi",
            "ho" to "Hiri Motu",
            "hu" to "Hungarian",
            "is" to "Icelandic",
            "io" to "Ido",
            "ig" to "Igbo",
            "id" to "Indonesian",
            "ie" to "Interlingue",
            "iu" to "Inuktitut",
            "ik" to "Inupiaq",
            "ga" to "Irish",
            "it" to "Italian",
            "ja" to "Japanese",
            "jv" to "Javanese",
            "kl" to "Kalaallisut",
            "kn" to "Kannada",
            "kr" to "Kanuri",
            "ks" to "Kashmiri",
            "kk" to "Kazakh",
            "km" to "Khmer",
            "ki" to "Kikuyu",
            "rw" to "Kinyarwanda",
            "ky" to "Kyrgyz",
            "kv" to "Komi",
            "kg" to "Kongo",
            "ko" to "Korean",
            "ku" to "Kurdish",
            "kj" to "Kwanyama",
            "la" to "Latin",
            "lb" to "Luxembourgish",
            "lg" to "Luganda",
            "li" to "Limburgish",
            "ln" to "Lingala",
            "lo" to "Lao",
            "lt" to "Lithuanian",
            "lv" to "Latvian",
            "gv" to "Manx",
            "mk" to "Macedonian",
            "mg" to "Malagasy",
            "ms" to "Malay",
            "ml" to "Malayalam",
            "mt" to "Maltese",
            "mi" to "Māori",
            "mr" to "Marathi",
            "mh" to "Marshallese",
            "mn" to "Mongolian",
            "na" to "Nauru",
            "nv" to "Navajo",
            "nd" to "Northern Ndebele",
            "ne" to "Nepali",
            "ng" to "Ndonga",
            "nb" to "Norwegian Bokmål",
            "nn" to "Norwegian Nynorsk",
            "no" to "Norwegian",
            "ii" to "Nuosu",
            "nr" to "Southern Ndebele",
            "oc" to "Occitan",
            "oj" to "Ojibwe",
            "cu" to "Old Church Slavonic",
            "om" to "Oromo",
            "or" to "Oriya",
            "os" to "Ossetian",
            "pa" to "Panjabi",
            "pi" to "Pāli",
            "fa" to "Persian",
            "pl" to "Polish",
            "ps" to "Pashto",
            "pt" to "Portuguese",
            "qu" to "Quechua",
            "rm" to "Romansh",
            "rn" to "Kirundi",
            "ro" to "Romanian",
            "ru" to "Russian",
            "sa" to "Sanskrit",
            "sc" to "Sardinian",
            "sd" to "Sindhi",
            "se" to "Northern Sami",
            "sm" to "Samoan",
            "sg" to "Sango",
            "sr" to "Serbian",
            "gd" to "Scottish Gaelic",
            "sn" to "Shona",
            "si" to "Sinhala",
            "sk" to "Slovak",
            "sl" to "Slovenian",
            "so" to "Somali",
            "st" to "Southern Sotho",
            "es" to "Spanish",
            "su" to "Sundanese",
            "sw" to "Swahili",
            "ss" to "Swati",
            "sv" to "Swedish",
            "ta" to "Tamil",
            "te" to "Telugu",
            "tg" to "Tajik",
            "th" to "Thai",
            "ti" to "Tigrinya",
            "bo" to "Tibetan",
            "tk" to "Turkmen",
            "tl" to "Tagalog",
            "tn" to "Tswana",
            "to" to "Tonga",
            "tr" to "Turkish",
            "ts" to "Tsonga",
            "tt" to "Tatar",
            "tw" to "Twi",
            "ty" to "Tahitian",
            "ug" to "Uyghur",
            "uk" to "Ukrainian",
            "ur" to "Urdu",
            "uz" to "Uzbek",
            "ve" to "Venda",
            "vi" to "Vietnamese",
            "vo" to "Volapük",
            "wa" to "Walloon",
            "cy" to "Welsh",
            "wo" to "Wolof",
            "fy" to "Western Frisian",
            "xh" to "Xhosa",
            "yi" to "Yiddish",
            "yo" to "Yoruba",
            "za" to "Zhuang",
            "zu" to "Zulu"
        )

    fun langCodeToName(code: String): String {
        return langCodes[code] ?: code
    }

    fun langNameUppercase(origin: String): String {
        return origin.substring(0, 1).uppercase(Locale.getDefault()) + origin.substring(1)
    }
}